version: "3.8"

services:
  url-shortener-api:
    image: url-shortener-api
    container_name: url-shortener-api
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    ports:
      - "10001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://url-shortener-postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
  url-shortener-postgres:
    image: postgres:16.0-alpine3.18
    container_name: url-shortener-postgres
    restart: always
    volumes:
      - ./deployments/postgres/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

networks:
  default:
    name: default_network
    external: true